# Generated by Django 6.0.5 on 2026-06-01 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="電子郵件"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=255, verbose_name="密碼雜湊"),
                ),
                (
                    "username",
                    models.CharField(max_length=50, verbose_name="使用者名稱"),
                ),
                ("total_points", models.IntegerField(default=0, verbose_name="總點數")),
                (
                    "last_checkin_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最後簽到時間"
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(default=0, verbose_name="連續簽到天數"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "顧客",
                "verbose_name_plural": "顧客列表",
            },
        ),
        migrations.CreateModel(
            name="PrinterSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="預設印表機", max_length=50, verbose_name="名稱"
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        choices=[(58, "58mm"), (80, "80mm")],
                        default=58,
                        verbose_name="紙張寬度",
                    ),
                ),
                ("font_size", models.IntegerField(default=1, verbose_name="字體大小")),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        help_text="網路印表機 IP。若使用 USB 則留空。",
                        max_length=50,
                        null=True,
                        verbose_name="IP 位址",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
            ],
            options={
                "verbose_name": "印表機設定",
                "verbose_name_plural": "印表機設定列表",
            },
        ),
        migrations.CreateModel(
            name="PrintTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="預設收據範本", max_length=50)),
                (
                    "content",
                    models.TextField(
                        help_text="支援變數: {{ table_number }}, {{ order_type }}, {{ items }}, {{ subtotal }}, {{ discount }}, {{ service_charge }}, {{ total }}",
                        verbose_name="範本內容",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
            ],
            options={
                "verbose_name": "列印範本",
                "verbose_name_plural": "列印範本列表",
            },
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255, verbose_name="操作內容")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="時間"),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="管理員",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日誌",
                "verbose_name_plural": "操作日誌列表",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分類名稱")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.category",
                        verbose_name="父分類",
                    ),
                ),
            ],
            options={
                "verbose_name": "分類",
                "verbose_name_plural": "分類列表",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="餐點名稱")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="價格"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="menu_photos/",
                        verbose_name="照片",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否上架"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.category",
                        verbose_name="分類",
                    ),
                ),
            ],
            options={
                "verbose_name": "餐點",
                "verbose_name_plural": "餐點列表",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("DINE_IN", "內用"), ("TAKEOUT", "外帶")],
                        max_length=10,
                        verbose_name="訂單類型",
                    ),
                ),
                (
                    "table_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="內用桌號"
                    ),
                ),
                (
                    "takeout_number",
                    models.IntegerField(blank=True, null=True, verbose_name="外帶號碼"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待確認中"),
                            ("CONFIRMED", "已確認/製作中"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="訂單狀態",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="小計"
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="折扣(%)",
                    ),
                ),
                (
                    "service_charge_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="服務費(%)",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="總計"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="確認員工",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.customer",
                        verbose_name="顧客",
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單",
                "verbose_name_plural": "訂單列表",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="數量"),
                ),
                (
                    "price_at_time",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="當時價格"
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "訂單項目",
                "verbose_name_plural": "訂單項目列表",
            },
        ),
    ]
