# Generated by Django 6.0.5 on 2026-06-02 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="low_stock_threshold",
            field=models.IntegerField(default=10, verbose_name="低庫存警示線"),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="stock_quantity",
            field=models.IntegerField(default=0, verbose_name="庫存數量"),
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("IN", "進貨/增加"),
                            ("OUT", "銷貨/扣除"),
                            ("ADJUST", "手動校正"),
                            ("WASTE", "報廢"),
                        ],
                        max_length=10,
                        verbose_name="異動類型",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="增加為正數，減少(如銷貨、報廢)也填寫正數，系統會依類型處理",
                        verbose_name="異動數量",
                    ),
                ),
                (
                    "remarks",
                    models.CharField(blank=True, max_length=255, verbose_name="備註"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="異動時間"),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transactions",
                        to="core.menuitem",
                        verbose_name="餐點項目",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人員",
                    ),
                ),
                (
                    "order_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.order",
                        verbose_name="關聯訂單",
                    ),
                ),
            ],
            options={
                "verbose_name": "庫存異動紀錄",
                "verbose_name_plural": "庫存異動紀錄列表",
                "ordering": ["-created_at"],
            },
        ),
    ]
